import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { Linking, Text, TouchableOpacity, View } from 'react-native';
import { MeetingSuggestion } from '../../../lib/places';

type Props = {
  suggestions: MeetingSuggestion[];
};

const TYPE_ICON: Record<string, keyof typeof Ionicons.glyphMap> = {
  'Shopping Mall': 'bag',
  'Coffee Shop': 'cafe',
  'Metro Station': 'train',
  'Bus Station': 'bus',
  'Police Station': 'shield-checkmark',
};

function getIcon(type: string): keyof typeof Ionicons.glyphMap {
  for (const key of Object.keys(TYPE_ICON)) {
    if (type.toLowerCase().includes(key.toLowerCase())) return TYPE_ICON[key];
  }
  return 'location';
}

export default function MeetSuggestionsCard({ suggestions }: Props) {
  return (
    <View className="px-4 py-2">
      <View className="bg-surface-cardLight dark:bg-surface-cardDark border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden">
        <View className="bg-brand-primary px-4 py-3 flex-row items-center">
          <Ionicons name="sparkles" size={18} color="#FFFFFF" />
          <Text className="ml-2 font-bold text-white text-sm">AI Meeting Spot Suggestions</Text>
        </View>

        {suggestions.map((spot, index) => (
          <TouchableOpacity
            key={index}
            onPress={() => {
              const query = encodeURIComponent(`${spot.name} ${spot.address}`);
              const googleUrl = spot.placeId
                ? `https://maps.google.com/?q=place_id:${spot.placeId}`
                : `https://maps.google.com/?q=${query}`;
              const appleUrl = `maps://?q=${query}`;
              Linking.canOpenURL(appleUrl).then(supported => {
                Linking.openURL(supported ? appleUrl : googleUrl);
              });
            }}
            className={`px-4 py-3 active:bg-slate-50 dark:active:bg-slate-800/50 ${index < suggestions.length - 1 ? 'border-b border-slate-100 dark:border-slate-800' : ''}`}
          >
            <View className="flex-row items-start">
              <View className="w-9 h-9 bg-brand-primary/10 rounded-full items-center justify-center mr-3 mt-0.5">
                <Ionicons name={getIcon(spot.type)} size={18} color="#0F766E" />
              </View>
              <View className="flex-1">
                <View className="flex-row items-center justify-between mb-0.5">
                  <Text className="font-bold text-text-primary dark:text-text-darkPrimary text-sm flex-1 mr-2">
                    {spot.name}
                  </Text>
                  <View className="bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-full">
                    <Text className="text-text-muted dark:text-text-darkMuted text-[10px] font-semibold">
                      {spot.type}
                    </Text>
                  </View>
                </View>
                <Text className="text-text-muted dark:text-text-darkMuted text-xs mb-1">
                  📍 {spot.address}
                </Text>
                <Text className="text-text-muted dark:text-text-darkMuted text-xs leading-relaxed">
                  {spot.reason}
                </Text>
              </View>
              <Ionicons name="chevron-forward" size={16} color="#94A3B8" style={{ marginTop: 2 }} />
            </View>
          </TouchableOpacity>
        ))}

        <View className="px-4 py-2 bg-surface-light dark:bg-surface-dark">
          <Text className="text-text-muted dark:text-text-darkMuted text-[10px] text-center">
            Suggestions generated by AI · Always meet in public
          </Text>
        </View>
      </View>
    </View>
  );
}
